### ISSUE TITLE
websocket-send-text: Cannot send message to a closed websocket: #s(websocket-frame text 

### ISSUE THREAD

**Issue by donaldsdlo** [ginqi7/dictionary-overlay#67]
![image](https://user-images.githubusercontent.com/17741154/207602990-0f53318c-b828-402f-beff-074b519fb841.png)

orjson                  3.8.2

(websocket-bridge-app-open-buffer 'dictionary-overlay)

`
WebSocket Client [dictionary-overlay] connected, the server port is 36479
Traceback (most recent call last):
  File "/home/donald/.emacs.d/site-lisp/dictionary-overlay/dictionary-overlay.py", line 341, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/donald/.emacs.d/site-lisp/dictionary-overlay/dictionary-overlay.py", line 299, in main
    await asyncio.gather(init(), bridge.start())
  File "/home/donald/.emacs.d/site-lisp/dictionary-overlay/dictionary-overlay.py", line 314, in init
    with open(dictionary_file_path, "r", encoding="utf-8") as f: dictionary = json_parser.load(f)
AttributeError: module 'orjson' has no attribute 'load'. Did you mean: 'loads'?

`

**Comment by ginqi7** [comment]
The last commit lack test. I revert the it. You could pull the new code.
